#!/bin/bash

set -eu

function test {
  local ver=$1; shift
  local cmd="docker-compose run spec crystal spec -v $@"

  echo "----------------------------------------------------------------------"
  echo "[$ver] $cmd"
  echo "----------------------------------------------------------------------"
  sed -i -e "s/^CRYSTAL_VERSION=.*/CRYSTAL_VERSION=$ver/" .env
  $cmd
}

test 0.27.2
test 0.33.0
test 0.34.0 --exclude-warnings lib
test 0.35.1 --exclude-warnings lib
