version: '2'

services:
  spec:
    image: crystallang/crystal:$CRYSTAL_VERSION
    command: crystal spec -v --exclude-warnings lib
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/v
    links:
      - clickhouse
    working_dir: /v
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123

  clickhouse:
    image: yandex/clickhouse-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
